Wdp201101-25
odevpl/wdp-2011-01 pull request #24
Opened 2020-11-12 21:10 UTC by Epps9

2020-11-13 15:15 UTC, odevpl requested changes

2020-11-13 15:15 UTC, odevpl commented on src/redux/saleRedux.js
> +export const getBargain = ({ saleContent }) => saleContent.bargain;
Te wszystkie gety do kosza. To czego potrzebujesz możesz spokojnie wyciągnąć w pliku wyżej bez dodatkowych funkcji... w Twoim projekcie miałaś filtry, więc dodatkowe funkcje miały sens... tu zamiast robić:

```
const obiektZProduktem = {product: [elementy]}
const dajProdukt = (produkt) => produkt.element;
const produt = dajProdukt(obiektZProduktem);
```
możesz poprostu wpisać w containerze:
```
const mapStateToProps = state => ({
  saleContent: state.saleContent
});
```

2020-11-13 15:15 UTC, odevpl commented on src/components/common/Sale/SaleContainer.js
> +import { connect } from 'react-redux';
Hej!
Mam jedną dużą uwagę. Zauważ, że Twoje funkcje nic nie robią, co za tym idzie, są nadmiarowe.
Proponuję wykasować wszystkie importy funkcji i zwrócić poprostu cały state.

Cały plik może wyglądać tak:
 ```
import { connect } from 'react-redux';
import Sale from './Sale';

const mapStateToProps = state => ({
 sale: state.saleContent
});

export default connect(mapStateToProps)(Sale);

2020-11-13 17:30 UTC, Epps9 commented on src/components/common/Sale/SaleContainer.js
> +import { connect } from 'react-redux';
Poprawione :) dzięki :)

2020-11-13 17:31 UTC, Epps9 commented
Wszystko poprawiłam, teraz powinno byc ok :)

2020-11-15 21:55 UTC, OJoachim reviewed
1. pobrano zip branch - by sprawdzić wyświetlanie się componentu strony
POJAWIA SIĘ:
```
Failed to compile

./src/components/features/BurgerMenu/BurgerMenu.js
Module not found: Can't resolve 'react-hamburger-menu' in 'D:\wdplus\kodillazad\wdp-2011-01\src\components\features\BurgerMenu'
```
NIE JEST TO BŁĄD EWY, NIE DOTYCZY JEJ COMPONENTU, Po naprawieniu tj.:
UWAGA linia4,13
```
import React from 'react';
import { Menu, MenuItem, MenuButton } from '@szhsin/react-menu';
import '@szhsin/react-menu/dist/index.css';
//import HamburgerMenu from 'react-hamburger-menu';
import { NavLink } from 'react-router-dom';

const BurgerMenu = () => {
  return (
    <Menu
      menuButton={
        <MenuButton>
          {' '}
          {/*<HamburgerMenu />{' '} */}
        </MenuButton>
```
strona wyświetla się prawidłowo    :-) 

2. ostylowanie jest poprawne poza ostylowaniem nagłówków - odbiega od zaleceń klienta,
dlatego zaproponowałam zmiany.  Na pewno jest lepszy sposób... 
3. Kod jest napisany czytelnie, tam gdzie powinno być wcięcie to ono jest...
Jedyna kwestia to jaki jest standard w tym projekcie 2 spacje czy 4 (lub tab) - po przeniesieniu do edytora wyświetlały mi się 4 spacje jako wcięcie (ale może zależy to od rodz. edytora...)

2020-11-15 21:55 UTC, OJoachim commented on src/redux/initialState.js
> +    content1: 'GUEST ROOM SOFA',
ponieważ ostylowanie strony odbiega od wyglądu w specyfikacji od klienta (chodzi o style nagłówków na tle 3 obrazów) i chciałabym poprawiać tylko fr. kodu dotyczące nagłówków - bez ingerencji w rozmieszczenie grida, flex itp, potrzebowałam rozdzielić wartość tekstową w "content1" content2 i 3, 

```
saleContent: {
    sofa: 'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg',
    goldenChair: 'https://images.pexels.com/photos/3932957/pexels-photo-3932957.jpeg',
    yellowChair: 'https://images.pexels.com/photos/4056469/pexels-photo-4056469.jpeg',
    bed: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg',
    content1a: 'GUEST ROOM',
    content1b: 'SOFA',
    bargain: '-20%',
    content2a: 'OFFICE ',
    content2b: 'CHAIR',
    content2c: 'COLLECTION',
    price: '$200.00',
    content3a: 'SPECIAL ',
    content3b: 'COLLECTION',
    info: 'SAVE UP 45% OF FURNITURE',
  },
};


export default initialState;
```

2020-11-15 21:55 UTC, OJoachim commented on src/components/common/Sale/Sale.js
> +          <h2>{saleContent.content1}</h2>
zmiany między 12 a 25 linią wynikają z poprawienia ostylowania (zmiana nagłówka, uzupełnienie wartości z saleContent (initialState.js)

```
       <div className={styles.firstPhoto}>
          <img src={saleContent.sofa} />
          <span></span>
          <h3>{saleContent.content1a}</h3>
          <h2>{saleContent.content1b}</h2>
          <h1>{saleContent.bargain}</h1>
        </div>
        <div className={styles.secondPhoto}>
          <img src={saleContent.yellowChair} />
          <h2><strong>{saleContent.content2a}</strong>{saleContent.content2b}</h2>
          <h4>{saleContent.content2c}</h4>
          <h3>{saleContent.price}</h3>
          <img src={saleContent.goldenChair} />
        </div>
        <div className={styles.thirdPhoto}>
          <img src={saleContent.bed} />
          <h3><strong>{saleContent.content3a}</strong>{saleContent.content3b}</h3>
          <h4>{saleContent.info}</h4>
        </div>
```

2020-11-15 21:55 UTC, OJoachim commented on src/components/common/Sale/Sale.module.scss
> +    h2 {
zmiany ostylowania - strona (nagłówki) nie wyświetlały się zgodnie (ja najbardziej w zbliżony sposób) z zaleceniami od klienta, proponowane zmiany związane są ze zmianami w Sale.js i initialState.js (saleContent):

```
.firstPhoto {
  grid-row-start:1;
  grid-row-end: 3;
  position: relative;

  img {
    height: 100%;
    width: 100%;
    object-fit: cover;
    position: relative;
  }
  h2 {
    position: absolute;
    bottom: 106px;
    left: 60px;
    color: $milk;
    font-size: 57px;
    text-shadow: 1px 1px  black;
    font-weight: bold;
  }
  h1 {
    position: absolute;
    bottom: 25px;
    left: 60px;
    color: $milk;
    border: 3px solid $milk;
    padding: 5px;
    font-size: 45px;
    text-shadow: 1px 1px $darkGrey;
    }
  h3 {
    position: absolute;
    bottom: 166px;
    left: 60px;
    color: $milk;
    font-size: 38px;
    text-shadow: 1px 1px $darkGrey;
  }
  span {
    background-color: $latte;
    width: 92%;
    height: 92%;
    position: absolute;
    opacity: 0.5;
    left: 20px;
    top:20px;
  }
}

.secondPhoto {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: 65% 35%;
  background-color: #EAEDF7;
  img {
    height: 100%;
    width: 100%;
    object-fit: cover;
    grid-row-start: 1;
    grid-row-end: 3;
  }
  h2 {
    grid-column-start: 2;
    grid-column-end: 3;
    grid-row-start: 2;
    grid-row-end: 3;
    color: $darkGrey;
    margin-top: -110px;
    margin-left: 5px;
    text-align: left;
    text-shadow: 3px 3px $white;
    font-size: 25px;
  }
  h4 {
    grid-column-start: 2;
    grid-column-end: 3;
    grid-row-end: 2;
    margin-left: 5px;
    margin-top: 138px;
    color: $darkGrey;
    font-size: 18px;
  }
  h3 {
    grid-column-start: 2;
    grid-column-end: 3;
    grid-row-end: 2;
    margin-left: 5px;
    margin-top: 190px;
    color: $primary;
    font-size: 25px;
    font-weight: bold;
  }
  
}

.thirdPhoto {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
  background-color: #FAF3F8;
  img {
    height: 100%;
    width: 90%;
    object-fit: cover;
    grid-row-start: 1;
    grid-row-end: 3;
  }
  h3 {
    grid-column-end: 3;
    grid-row-end: 2;
    color: $primary;
    margin-top: 120px;
    margin-right: 12px;
    text-align: right;
    text-shadow: 3px 2px $milk;
    font-size: 25px;
  }
  h4 {
    grid-column-end: 3;
    grid-row-start: 2; 
    color: $darkGrey;
    margin-bottom: 130px;
    margin-right: 12px;
    text-align: right;
    text-shadow: 3px 2px $milk;
    font-size: 16px;
  }
}
```

2020-11-15 21:59 UTC, OJoachim commented
Code Review do zad WPD201101-25 #24, dotyczącego stworzenia komponentu Sale, zad. nie dotyczyło RWD

2020-11-15 22:37 UTC, OJoachim reviewed
code review do WDP201101-25 #24

2020-11-16 22:27 UTC, Epps9 commented
Zmieniłam wygląd komponentu. Teraz powinien być ok.

2020-11-19 02:15 UTC, OJoachim approved these changes

2020-11-20 22:10 UTC, odevpl approved these changes

2020-11-20 22:10 UTC, merged