Wdp201101 40
odevpl/wdp-2011-01 pull request #35
Opened 2020-11-17 19:16 UTC by Epps9

Banner component

2020-11-19 22:14 UTC, joanna-stachowicz commented on src/components/features/Banner/Banner.js
> +const Banner = ({ bannerData }) => (
Może lepiej byłoby użyć kilku osobnych propsów zamiast obiektu. Czy np. 
`const Banner = ({ description, bargain })`
a w BannerContainer wewnątrz mapStateToProps wystarczy `...state.bannerData,`

2020-11-19 22:15 UTC, joanna-stachowicz commented on src/components/features/Banner/BannerContainer.js
> +  bannerData: state.bannerData,
Zobacz mój powyższy komentarz.

2020-11-20 23:01 UTC, joanna-stachowicz requested changes
Ogólnie podoba mi się - ładnie to napisałaś. Tylko kilka drobnych uwag.

2020-11-20 23:01 UTC, joanna-stachowicz commented on src/redux/initialState.js
> +    furniture: 'firniture',
Literówka ;)

2020-11-21 18:30 UTC, Epps9 commented on src/components/features/Banner/BannerContainer.js
> +  bannerData: state.bannerData,
tak jak wyżej ...state.bannerData nie działa

2020-11-21 18:30 UTC, Epps9 commented on src/components/features/Banner/Banner.js
> +const Banner = ({ bannerData }) => (
Niestety w połaczeniu ze zmianami w kontenerze to rozwiązanie nie działa. zwraca błąd dla ...state.bannerData

2020-11-21 18:36 UTC, Epps9 commented on src/components/features/Banner/Banner.module.scss
> +    background-color: #363636;
good point! poprawione :)

2020-11-21 18:36 UTC, Epps9 commented on src/redux/initialState.js
> +    furniture: 'firniture',
dzięki :)

2020-11-21 21:04 UTC, joanna-stachowicz commented
Hej Ewa! Zacommitowałam zmiany, żeby Ci pokazać, o co mi chodziło. Trzeba by było jeszcze tylko poprawić propTypes.

2020-11-21 21:06 UTC, joanna-stachowicz requested changes
Hej Ewa! Zacommitowałam zmiany, żeby Ci pokazać, o co mi chodziło. Trzeba by było jeszcze tylko poprawić propTypes.

2020-11-23 21:06 UTC, joanna-stachowicz approved these changes

2020-11-24 08:09 UTC, merged