WDP201101-47
odevpl/wdp-2011-01 pull request #40
Opened 2020-11-20 21:14 UTC by BartoszHor

Zadanie wykonane ale z uwagi na brak zaakceptowanego zadania dotyczącego podziału na dwie kolumny na podstronie shop, póki co umieściłem komponent po prostu w komponencie ProductList. Wizualnie odpowiada wymaganiom ticketa natomiast trzeba go później "wpasować" w całość.

2020-11-20 22:48 UTC, joanna-stachowicz requested changes
Ogólnie ładny kod. Tylko parę drobnych uwag.

2020-11-20 22:48 UTC, joanna-stachowicz commented on package-lock.json
> +    "react-spring": {
Nie znam tego komponentu` react-spring`. Gdzie on jest użyty?

2020-11-20 22:48 UTC, joanna-stachowicz commented on src/components/features/CategoryFilter/CategoryFilter.js
> +export default CategoryFilter;
Fajnie, że w kilku linijkach udało Ci się osiągnąć taki ładny efekt ;)

2020-11-20 22:48 UTC, joanna-stachowicz commented on src/components/features/CategoryFilter/CategoryFilter.js
> +  map: PropTypes.func,
Czy używasz gdzieś tego mapa?

2020-11-20 22:48 UTC, joanna-stachowicz commented on src/components/features/CategoryFilter/CategoryFilter.module.scss
> +    border-bottom: 2px solid gray;
Nie wiem, czy nie powinniśmy używać tylko tych kolorów z settingsów?

2020-11-22 06:57 UTC, BartoszHor commented on package-lock.json
> +    "react-spring": {
to sie automatycznie zainstalowalo.

2020-11-22 07:01 UTC, BartoszHor commented on src/components/features/CategoryFilter/CategoryFilter.js
> +export default CategoryFilter;
no fajnie.

2020-11-22 07:02 UTC, BartoszHor commented on src/components/features/CategoryFilter/CategoryFilter.js
> +  map: PropTypes.func,
mapuje categories

2020-11-22 07:03 UTC, BartoszHor commented on src/components/features/CategoryFilter/CategoryFilter.module.scss
> +    border-bottom: 2px solid gray;
temat styli globalnych jest nierozwiązany do dziś także użyłem tak koloró by wyglądały podobnie do tych z "wymagań klienta"

2020-11-22 15:16 UTC, joanna-stachowicz approved these changes

2020-11-22 21:27 UTC, merged