Wdp201101 23
odevpl/wdp-2011-01 pull request #42
Opened 2020-11-22 12:21 UTC by Hiorii

2020-11-22 18:53 UTC, joanna-stachowicz requested changes
Napisałam kilka komentarzy szczegółowych do kodu, ale jeszcze mam kilka ogólnych uwag:

- Animacja slidera po prawej stronie jest za wolna - nie pasuje do reszty strony; strona wygląda jakby była zepsuta.
- W sliderze po lewej stronie podczas animacji znika cały komponent. Lepiej jakby znikało tylko samo zdjęcie. Buttony na pewno nie powinny znikać całkowicie - cały czas powinna być możliwość ich kliknięcia.
- Po przeczekaniu 10 sek. kiedy się kliknie na którąś kropkę, coś dziwnego zaczyna się z nimi dziać. Np. mi przeszło tak: 1 kropka, 2, 1 i 3. Ale generalnie różnie się to zmienia.
- Odliczanie do końca promocji powinno być raczej widoczne cały czas, a nie tylko na hover.
- Widok cen na dole wygląda inaczej niż na makiecie.

2020-11-22 18:53 UTC, joanna-stachowicz commented on src/redux/initialState.js
> +<<<<<<< HEAD
Tutaj są nierozwiązane konflikty.

2020-11-22 18:53 UTC, joanna-stachowicz commented on src/components/features/PromoProducts/PromoProducts.js
> +      item => item.name === 'Bed' || item.name === 'Chair' || item.name === 'Sofa'
Może lepiej byłoby dopisać w InitialState do obiektów wewnątrz categories  kolejną właściwość newCategory: true lub false i później w tym miejscu coś w tym stylu: `item => item.newCategory === true`

2020-11-22 18:53 UTC, joanna-stachowicz commented on src/components/common/PromoProductBox/PromoProductBox.js
> +        <div className={styles.content}>
Istnieje już komponent stars, którego można by tutaj użyć.

2020-11-23 17:01 UTC, Hiorii commented on src/components/common/PromoProductBox/PromoProductBox.js
> +        <div className={styles.content}>
Dzięki!
Poprawione :)

2020-11-23 19:21 UTC, Hiorii commented on src/components/features/PromoProducts/PromoProducts.js
> +      item => item.name === 'Bed' || item.name === 'Chair' || item.name === 'Sofa'
Również fajna uwaga. Dodane w initial state ;)

2020-11-23 19:21 UTC, Hiorii commented on src/redux/initialState.js
> +<<<<<<< HEAD
Poprawione.

2020-11-23 19:38 UTC, Hiorii commented
Co do uwag:
- Animacja slidera po prawej stronie jest za wolna - nie pasuje do reszty strony; strona wygląda jakby była zepsuta.
**Zmienione. Ustawiłem osobne animacje dla prawego i lewego kontenera.**

- W sliderze po lewej stronie podczas animacji znika cały komponent. Lepiej jakby znikało tylko samo zdjęcie. Buttony na pewno nie powinny znikać całkowicie - cały czas powinna być możliwość ich kliknięcia.
**Tutaj nie do końca się zgodzę. Buttony są indywidualnie przypisane do renderowanego zdjęcia. Na przykład, jeśli dany produkt będzie ulubiony - to serduszko z automatu będzie pomarańczowe. Dlatego  po analizie - moim zdaniem za każdym razem musi przeładowywać się całość.**

- Po przeczekaniu 10 sek. kiedy się kliknie na którąś kropkę, coś dziwnego zaczyna się z nimi dziać. Np. mi przeszło tak: 1 kropka, 2, 1 i 3. Ale generalnie różnie się to zmienia.
**Hmm. Tutaj ciężko mi powiedzieć o co chodzi, bo u mnie problem się nie pojawia.**

- Odliczanie do końca promocji powinno być raczej widoczne cały czas, a nie tylko na hover.
**Musi być widoczne na hoover bo taki był wymóg klienta (czytaj tak było w polecaniu do taska)**

- Widok cen na dole wygląda inaczej niż na makiecie.
**Poprawione.**

2020-11-23 19:47 UTC, Hiorii reviewed
Changes implemented.

2020-11-23 21:05 UTC, joanna-stachowicz approved these changes

2020-11-24 08:08 UTC, merged